## 一、箭头函数能否执行显示绑定
```js
  const a = 2;
  var b = 4;
  const myObj = {
    a: 1,
    b: 3
  }
  const myFunc = () => {
    console.log(this.a);
    console.log(this.b);
  }
  myFunc();
  //undefined
  //4

  const myFuncNew = myFunc.bind(myObj);
  myFuncNew();
  //undefined
  //4

  console.log('func2');

  function myFunc2() {
    console.log(this.a);
    console.log(this.b);
  }
  myFunc2();
  //undefined
  // 4
  
  const myFunc2New = myFunc2.bind(myObj);
  myFunc2New();
  //1
  //3
```
### 结论
箭头函数无法执行显式绑定

## 二、async await后面加promise，该promise抛出错误会怎么样？
promise放在try...catch里面
### promise放在try..catch里面
```js
try {
  new Promise((resolve, reject) => {
    setTimeout(resolve, 1000, '1')
  })
} catch(err) {
  console.log(err);
}
//结果：Promise {<pending>}
```

```js
try {
  new Promise((resolve, reject) => {
    reject('err')
  })
} catch(err) {
  console.log(err);
}
//Promise {<rejected>: "err"} 
//浏览器控制台报错 Uncaught (in promise) err
```

```js
try {
  new Promise((resolve, reject) => {
    setTimeout(reject, 1000,'err')
  })
} catch(err) {
  console.log(err);
}
//Promise {<pending>}
//浏览器控制台报错: Uncaught (in promise) err
```

可知: try...catch无法捕获异步错误，即无法捕获promise的错误。

但promise自己的catch可以捕获自己的错误。Promise 对象的错误具有冒泡性质，会一直向后传递，直到被捕获为止，也即是说，错误总会被下一个catch语句捕获。

### promise放在async中的await后面
```js
async function getResultOfPromise() {
  const result = await new Promise((resolve, reject) => {
    setTimeout(resolve, 1000, '1');
  });
  console.log(result);//1
  const result2 = await new Promise((resolve, reject) => {
    setTimeout(reject, 1000, '2');
  })
  console.log(result2);//Uncaught (in promise) 2: (控制台报错)
}
getResultOfPromise();
```

### 结论
await只能获取promise的resolve的值，无法获取reject的值，如果后面接的是reject的值，那么控制台只能报错。

## 三、有没有用过react的forceUpdate() ？
forceUpdate()
#### 语法
```js
component.forceUpdate(callback);
```

#### 解读
默认情况下，当组件的state或props发生更改时，组件将重新呈现。如果render()依赖于其他一些数据，则可以通过调用forceUpdate()告诉React该组件需要重新呈现。

调用forceUpdate()将导致在组件上调用render(),跳过shouldComponentUpdate()。这将触发子组件的正常生命周期方法，包括每个子组件的shouldComponentUpdate()方法。

#### 示例
forceUpdate就是重新render。有些变量不在state上，当时你又想达到这个变量更新的时候，刷新render；或者state里的某个变量层次太深，更新的时候没有自动触发render。这些时候都可以手动调用forceUpdate自动触发render

Sub.js：
```js
class Sub extends React.Component{
    construcotr(){
        super();
        this.name = "yema";
    }
    refChangeName(name){
        this.name = name;
        this.forceUpdate(); 
    }
    render(){
        return (<div>{this.name}</div>);
    }
}
```
App.js:
```js
class App extends React.Component{

    handleClick(){
        this.subRef.refChangeName("yemafuren");
    }
    render(){
        return (<div>
            <Sub ref={(sub)=>{this.subRef = sub;}} />
            <button onClick={this.handleClick}>click</button>
        </div>);
    }
}  
```